### ISSUE TITLE
exposing parse_headers() for parsing multipart/form-data

### ISSUE THREAD

**Issue by mikedilger** [seanmonstar/httparse#10]
I'm trying to parse `multipart/form-data` form submissions.  I can extract and pass on the header lines of each part into a parser.  But which parser?  parse_headers() is private and its not obvious how to use it.  Advice?

**Comment by seanmonstar** [comment]
It seems reasonable to expose a free function `parse_headers`.

**Comment by mikedilger** [comment]
Thanks!  I like the changes
