### ISSUE TITLE
Remove trailing whitespace from header field values

### ISSUE THREAD

**Issue by pyfisch** [seanmonstar/httparse#15]
[RFC7230#Field parsing](https://tools.ietf.org/html/rfc7230#section-3.2.4) states that parsers should remove leading in trailing whitespace from header field values. Currently httparse only removes leading whitespace, removing trailing whitespace would make httparse easier to use for other crates.

The following two requests should be parsed the same:
- `GET / HTTP/1.1\r\nHost: foo.com\r\nUser-Agent: foobarsoft\r\n\r\n`
- `GET / HTTP/1.1\r\nHost: foo.com\r\nUser-Agent: foobarsoft \t \t \r\n\r\n`

**Comment by seanmonstar** [comment]
Something to keep in mind if implementing this is to do so without losing
much performance.

**Comment by seanmonstar** [comment]
This was done in #48.
