### ISSUE TITLE
How to parse body from request or response?

### ISSUE THREAD

**Issue by natemara** [seanmonstar/httparse#16]
I'm not sure if this is the right place to ask this, but I'm looking through the documentation, and I don't see how I could use this library to get the body of a request or a response. Neither of the two structs have a field for body, and the `parse` method just gives back an index, is that the starting byte-index of where the body should begin?

**Comment by seanmonstar** [comment]
Yes. Really, it's the length of the "head". Everything after is the body,
whose parsing is likely dependent on the headers, such as if it's chunked,
gzipped, etc.

**Comment by Fedcomp** [comment]
but why not make handy method that returns body slice? Seems so intuitive to make it. Is there any perfomance reasons not to?

**Comment by Fedcomp** [comment]
How do i get the lenght of the head then? any method for that?

**Comment by seeekr** [comment]
Sorry to necro an old issue, but I think (hope) this fits here:

So is it correct then to say that this crate does not concern itself, and neither does it want to concern itself, with parsing the HTTP message body?
I would be happy to add a little bit of documentation stating that clearly in the right places, seeing as this is one of the first results that come up when one would be looking for crates that parse http messages.

Is there an explanation for the lack of support for the http body? I could imagine that a primary use case for this library is handling HTTP/1.0 and 1.1 without chunked encoding, and so finding the body is basically trivial to implement?
