### ISSUE TITLE
Weird header parsing in 1.9

### ISSUE THREAD

**Issue by Tpt** [seanmonstar/httparse#172]
Thank you so much for `httparse` all your other amazing libraries.

Sorry for the maybe bad bug report, I am not a HTTP expert.

With the new 1.9 version I get a test regression in [oxhttp](https://github.com/oxigraph/oxhttp) with strange parsing result. A `:` gets included in one of the header value.

Here is a test to reproduce the possible regression:

```rust
    #[test]
    fn test_http_parse() {
        let mut headers = [httparse::EMPTY_HEADER; 1024];
        let mut parsed_request = httparse::Request::new(&mut headers);
        parsed_request
            .parse(b"POST / HTTP/1.1\ncontent-length:4\n\n")
            .unwrap();
        for header in parsed_request.headers {
            if header.name == "content-length" {
                assert_eq!(header.value, b"4"); // Fails, we get ':4'
            }
        }
    }
```

Thank you again for your library.

**Comment by seanmonstar** [comment]
Thanks for the report, PR at #174.

**Comment by Tpt** [comment]
Thank you!
