### ISSUE TITLE
User-triggerable UB in Bytes::peek_ahead bounds-check

### ISSUE THREAD

**Issue by Manishearth** [seanmonstar/httparse#177]
https://github.com/seanmonstar/httparse/blob/ab76284909497def188de96b1b1431a0cfcf6cf4/src/iter.rs#L45-L49

[`ptr::add`](https://doc.rust-lang.org/std/primitive.pointer.html#method.add) has the following safety conditions:

- If the computed offset, in bytes, is non-zero, then both the starting and resulting pointer must be either in bounds or at the end of the same [allocated object](https://doc.rust-lang.org/std/ptr/index.html#allocated-object). (If it is zero, then the function is always well-defined.)

 - The computed offset, in bytes, cannot overflow an isize.

 - The offset being in bounds cannot rely on “wrapping around” the address space. That is, the infinite-precision sum must fit in a usize.

This is fixable by performing the bounds-check differently.

This is probably not an actual problem with current rustc but could be in the future

**Comment by seanmonstar** [comment]
Interesting!

@AaronO do you recall if ordering the compare after the add was important? It seems like we need to do it different, but just wondering before I reach for the most obvious refactor.
