### ISSUE TITLE
parse_chunk_size can have integer overflow

### ISSUE THREAD

**Issue by jethrogb** [seanmonstar/httparse#19]
AFAICT the HTTP spec does not limit the chunk size. Yet, `parse_chunk_size` tries to parse it into a `u64`. If a value is provided that doesn't fit in a `u64`, the multiplication operator will overflow in release mode or panic in debug mode. Instead, the function should return an error. This might be a good use for [checked_mul](https://doc.rust-lang.org/stable/std/primitive.u64.html#method.checked_mul).

**Comment by seanmonstar** [comment]
Good point. Looking elsewhere for example behavior, it seems in golang, a chunk size is just rejected if it is too big: https://github.com/golang/go/blob/3caf4e05cf337fa9b395dd887aa3e8d2e26eecdf/src/net/http/internal/chunked.go#L234-L236

It'd be incorrect to report a chunk size is `u64::MAX` when the hex value actually describes a bigger number. Probably best to return an `Err` in that case.
