### ISSUE TITLE
use Option<NonZeroU16> instead of Option<u16> for Response status

### ISSUE THREAD

**Issue by ramiroaisen** [seanmonstar/httparse#195]
Using NonZeroU16 for responses  status codes allows Rust to do some clever optimizations, such as using the the zero case for storing the None value in options, reducing the field size to 2 bytes instead of 4 for response.code. Right now response.code occupies 4 bytes and not 3 because of aligning as far as I understand

**Comment by seanmonstar** [comment]
It would be nice, but it's currently a breaking change, since it changes the type that people can access. Maybe in some hypothetical v2 (but that's not planned).
