### ISSUE TITLE
`parse_headers()` enables undefined behavior

### ISSUE THREAD

**Issue by abonander** [seanmonstar/httparse#34]
Simplest reproduction.

```rust
extern crate httparse;

use httparse::{EMPTY_HEADER, parse_headers};

fn main() {
    let mut buf = *b"Foo: Bar\r\n\r\n";

    let mut headers = [EMPTY_HEADER];

    let headers_len = {
        let (_, headers) = parse_headers(&mut buf, &mut headers).unwrap().unwrap();
        headers.len()
    } ;

    assert_eq!(headers_len, 1);

    buf[0] = b'B';

    // Prints "Boo"
    println!("{:?}", headers[0].name);
}
```

As you can see, `parse_headers()` allows borrows to `buf` to escape in `headers`, creating a double-borrow where the original buffer can be mutated while views to it exist.

Discovered by accident, I was working on some infinite-loop bugs in multipart when I took a double-take at [this function](https://github.com/abonander/multipart/blob/ef876d8c043ecc92cda87a4d433811595f429f9b/src/server/field.rs#L48) and thought, "Wait a minute, how the hell did this work to begin with?" The `r.consume()` at 80 shouldn't be allowed, but the borrow is escaping.

**Comment by seanmonstar** [comment]
I believe this is caused by the implementation of the internal `shrink` function, which is just trying to shorten the reference it has to the headers slice. In my experimenting, it doesn't seem to be immediately obvious how to do so and make the borrow checker happy...

**Comment by abonander** [comment]
Holy crap, this may be Rust's failing unless I'm fundamentally misunderstanding something here: https://is.gd/pFdpPJ

**Comment by abonander** [comment]
So yeah, it's a bug with Rust, haha.

**Comment by seanmonstar** [comment]
@abonander Whew! I was genuinely staring at this last night, and wondering "but, I have lifetimes specified, how did I screw this up?!"

**Comment by abonander** [comment]
rust-lang/rust#40288 is closed now and any breakage was addressed via Crater run so I think this is safe to close now.
