### ISSUE TITLE
use with ringbuffer

### ISSUE THREAD

**Issue by jkarneges** [seanmonstar/httparse#44]
Hi,

First, thanks for this great library!

Is it possible to parse around the edge of a ring buffer boundary? E.g by providing two buffers as input to the parser? Currently I'm shifting all remaining bytes down after every successful parse but it would be nice to not have to do that. Any advice?

**Comment by seanmonstar** [comment]
I think it could be nice to have an API that takes a [`Buf`](https://docs.rs/bytes/0.4.*/bytes/trait.Buf.html). That'd allow ring buffers, and any other instance where you don't have the bytes in contiguous memory.

However, there'd definitely be a performance cost to that, so I don't think it could be the default API... Hm, it might actually be annoying to figure out how to get that to all work nicely...

**Comment by seanmonstar** [comment]
You don't necessarily need to memmove with pipelined requests. If you're using some sort of cursor, you can just pass the rest of the buffer to be parsed after having finished with the previous request. If you get a partial result back, you can then decide whether to consolidate or just keep reading into the end.

**Comment by jkarneges** [comment]
Good point. Consolidating when data has already wrapped around can be tricky though, which is why I was shifting after each read to ensure that couldn't happen. But perhaps I can optimize this.
