### ISSUE TITLE
httparse should skip invalid headers

### ISSUE THREAD

**Issue by Coder-256** [seanmonstar/httparse#61]
I am trying to use `reqwest` to parse a response from a server I don't control. `reqwest` uses `hyper` which uses `httparse` for parsing HTTP/1.x headers. Anyway, this server has a weird bug where it consistently returns a single corrupted header line in an otherwise completely valid response (the header contains unescaped non-token characters). Specifically, for some reason it tries to send the `DOCTYPE` as a header. The bug is unlikely to be fixed (this is old software), but it isn't really a problem because the page displays fine in all major browsers.

It seems that all major browsers simply ignore invalid header lines. However, `httparse` returns an error that aborts the entire parsing process. IMO this is a problem and should be fixed.

Here's a screenshot from Chrome that shows the invalid header being ignored:

<img width="266" alt="ignored" src="https://user-images.githubusercontent.com/10134823/64579495-20f13080-d351-11e9-93f6-b9d7538b1122.png">
<img width="853" alt="original" src="https://user-images.githubusercontent.com/10134823/64579510-29e20200-d351-11e9-9fbe-c73487f04947.png">

In fact, Chrome's behavior is commented as: ["skip malformed header"](https://chromium.googlesource.com/chromium/src/+/b6532ab4077e913e38d99f5a970e437516643d03/net/http/http_util.cc#935).

Although technically changing this could be breaking, in this case, I can't imagine that any code would rely on response parsing to *fail* in this particular case.

Here are the relevant lines:

https://github.com/seanmonstar/httparse/blob/6f696f5d027f35e11a70181c839b574e20335a74/src/lib.rs#L594-L595

https://github.com/seanmonstar/httparse/blob/6f696f5d027f35e11a70181c839b574e20335a74/src/lib.rs#L613-L614

https://github.com/seanmonstar/httparse/blob/6f696f5d027f35e11a70181c839b574e20335a74/src/lib.rs#L672

https://github.com/seanmonstar/httparse/blob/6f696f5d027f35e11a70181c839b574e20335a74/src/lib.rs#L613-L614

I think all of these would be fixed by consuming `b` until the next newline then `continue 'headers`. I would open a PR but I just want to check that you agree that this change should be made.

**Comment by seanmonstar** [comment]
Hm, I'm surprised at the results, but then again, I shouldn't be, the HTTP1 spec has been ignored at every turn :D

Curious, do you know what other "libraries" do, like curl or golang?

**Comment by Coder-256** [comment]
I haven't tested this, but it looks like [`golang` errors on headers missing a colon](https://github.com/golang/go/blob/e6ad619ad673d7484535afd4185209b0e9aa95c8/src/net/textproto/reader.go#L503) but otherwise just parses it as a valid header

I also have confirmed that `curl` actually parses it as a valid header:

```
$ curl "$URL" -s -o /dev/null -D -
HTTP/1.1 200 OK
Date: Tue, 10 Sep 2019 18:50:02 GMT
Server: Apache/2.4.xx (Debian)
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http: //www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
Transfer-Encoding: chunked
```

I took a quick look but its code is very dense. The header parsing logic is around `Curl_http_readwrite_headers` if you want to look further. It should be noted that `curl` doesn't actually do anything with headers except for important ones (ex. `Transfer-Encoding`). In fact AFAIK the most it will do in terms of parsing arbitrary headers is give you the entire message header with `-D` like above.

It was a good idea to check these libraries, I didn't realize that they would handle things differently. I guess there are 3 behaviors to choose from:

- Ignore invalid headers (like Chrome, Firefox, etc.)
- Pass on invalid headers (like `curl` and `golang`)
- Error on invalid headers (like `httparse`)

I'll need to think a bit more about which would be better. What do you think?

**Comment by Coder-256** [comment]
@seanmonstar Have you had a chance to look into this?

**Comment by seanmonstar** [comment]
Oh my, I completely forgot about this issue, sorry!

I suppose it makes sense to do what browsers do. I have a nagging worry that if ignore invalid headers, is there a point where we're parsing things that *really* aren't HTTP and saying it is?

**Comment by Coder-256** [comment]
Well if the status line is intact, including HTTP version and all, I think it's definitely supposed to be HTTP. The headers are only parsed if the status line is valid.

I'll start making the PR.

**Comment by nox** [comment]
FWIW this behaviour was completely killed from Squid last year.

https://github.com/squid-cache/squid/commit/b453677bc1de131d88bf865d01afdc69dcef37a2

**Comment by nox** [comment]
@Coder-256 Did you ever make a patch for this?

Found another website affected by this.

```
curl -I https://dbegoals.azdot.gov/
```

```
00000000  58 e2 80 90 46 72 61 6d  65 e2 80 90 4f 70 74 69  |X...Frame...Opti|
00000010  6f 6e 73 3a 20 44 45 4e  59                       |ons: DENY|
```

The hyphens aren't ASCII in the first `X-Frame-Options` entry.

**Comment by nox** [comment]
https://github.com/seanmonstar/httparse/pull/114 will let you ignore the invalid header.

**Comment by Coder-256** [comment]
@nox Thank you very much, lgtm! Sorry I didn’t get to this sooner.
