### ISSUE TITLE
A way to ignore headers completely

### ISSUE THREAD

**Issue by Fedcomp** [seanmonstar/httparse#63]
For my purpose i need to completely ignore headers, i am only interested in request method and path.

Is there a way to ignore `TooManyHeaders` error and get all other request data?

**Comment by seanmonstar** [comment]
Yes, of course. I've done it this way before: create a `Request` with a 0-length headers slice, call `req.parse(data)`, and then match on the result. If you got an `Err(TooManyHeaders)`, you know it parsed the method, path, and version. Those fields will be set to `Some`.

**Comment by Fedcomp** [comment]
Oh sorry! i did the same but forgot i could still access the request. I am sorry.
