### ISSUE TITLE
Allow providing a list of expected headers

### ISSUE THREAD

**Issue by ctron** [seanmonstar/httparse#79]
When parsing a response, the number of headers is limited.

However, if an application knows upfront which headers it cares about, all other headers could be ignored, and simply skipped from returning.

It would be great if the user could provide a list of "expected" (or "allowed") headers. And only those headers would get recorded for the result.

**Comment by seanmonstar** [comment]
This could be an interesting thing to do! However, I think it's out of scope of this library, as it seems rather niche. Therefore, I'm going to close up here.
