### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by PawelLawrynowicz** [seanmonstar/httparse#90]
In the "Usage" part of the README file:
```
assert!(req.parse(buf)?.is_partial());
```

throws an error:
```
cannot use the ? operator in a function that returns ()
```

The correct usage is as in the documentation:
```
req.parse(buf).unwrap().is_partial()
```

**Comment by songww** [comment]
Your test func should return `httparse::Result<()>` to use `?` for early return.
